### ISSUE TITLE
Add "keep-alive" option

### ISSUE THREAD

**Issue by MacroPower** [MacroPower/macropower-analytics-panel#12]
From #10 

> Another idea I have in mind is a "keep-alive" option: since the plugin can't send the end request when the browser window is closed, it could send a keep alive to the server every x minutes. The server could than be configured to consider a session ended if it didn't receive a keep-alive for more than x+1 minutes (or more) which could still be overwritten if the end request comes in. - @jtommi

I really like this idea and think it could really help solve a number of issues with the data this plugin delivers. I'm opening up this issue to track progress.

**Comment by MacroPower** [comment]
@jtommi Let me know if you want to take a stab at this. If not, I'll probably be able to get around to it in the next few weeks. 🙂

**Comment by jtommi** [comment]
Yeah I think I can manage that. If not, we'll see when you have time.
My idea is to not define a frequency but simply use the auto-refresh built-in. If it's 5 seconds (meaning all other panels are updated every 5 seconds) then that's the frequency of the keep-alive.

What I'm less sure about: should you be able to choose a different path for the keep-alive messages than for the end message ?

In my implementation of the listener, I would handle every message the same, whether it's keep-alive or end; each time one comes in, I update the session end-time in my db.
That said, if someone would want to implement a listener that shows the currently active sessions for a dashboard, the end message would be used to know "the user left" and basically delete the session.
You could use the same path but GET or PUT instead of POST, but that's not the cleanest option either.

**Comment by MacroPower** [comment]
> My idea is to not define a frequency but simply use the auto-refresh built-in. If it's 5 seconds (meaning all other panels are updated every 5 seconds) then that's the frequency of the keep-alive.

While this may work in some cases, I think it would be better to be independent of the auto-refresh, simply because not every dashboard uses it. For instance, if I have a dashboard for my capacity over the past 1 year, I'm not going to be auto-refreshing it, but I still might want to know exactly how long a user was on the page.

Another thing to consider is users leaving dashboards open in the background, or in a seperate tab. I think keep-alive should only be sent when the dashboard is active/in focus. That way in the listener implementation you can (if you want) get a much better idea of how much time is being spent on a dashboard. This is really similar to how services like Wakatime work.

> should you be able to choose a different path for the keep-alive messages than for the end message?

I think there should definitely be some way to distinguish keep-alive vs end messages. We could add a new property to the body, e.g. "eventType", and set it to "start", "keep-alive", or "end". Later on, this could open the doors for other events as well, e.g. "refresh".

**Comment by MacroPower** [comment]
This is closed in #13. One note is that I've decided to call the payloads "heartbeats" rather than "keep-alives" because I think this more clearly conveys what they do, and avoids confusion with the `connection` property of fetch.
