### ISSUE TITLE
Editing defaults - dist/defaults.json does not exist

### ISSUE THREAD

**Issue by onefourfive** [MacroPower/macropower-analytics-panel#17]
Per the README

> You can edit defaults by changing the `dist/defaults.json` file. 

However no `defaults.json` file (or example) is provided in `dist`. How should defaults be configured?

**Comment by onefourfive** [comment]
I've tested changing the defaults.json in the `data/plugins/macropower-analytics-panel/src/` directory, and also moving that file into `data/plugins/macropower-analytics-panel/dist/`, but neither location seemed to have an effect.

**Comment by MacroPower** [comment]
Hey @onefourfive sorry about this. The grafana plugin toolkit inlines the file in the current version of the plugin. You can either edit the dist/module.js file `... {t.exports=JSON.parse('{"endpoint":"http://localhost:8080", <...>}')` or you can edit the `src/defaults.json` and re-compile the plugin via `npm run build` (should inline your changes). In a future release this file will be copied over and the behavior described in the readme should be correct again.

**Comment by MacroPower** [comment]
After looking into this further, I've decided to not copy the file and keep things inline. I've updated the documentation to reflect that. I made this decision because separating the files would have required an additional fetch on each dashboard load. I felt the negatives outweighed the benefits of being able to edit the default config without running `npm run build`.

I'm closing this issue, but if you have any additional comments or need help building the plugin, please feel free to re-open this.
