### ISSUE TITLE
Add option to avoid including personally identifiable information in collected data

### ISSUE THREAD

**Issue by mig4** [MacroPower/macropower-analytics-panel#22]
Hi, thanks for the plugin, it looks great! We're looking into using it in a couple of our dashboards at Giant Swarm.

What do you think of an option to avoid including any personally identifiable information in the collected data? I'm thinking specifically about `user.login` and `user.email` fields (aka `user_login` and `user_email` labels on metrics).

I'm aware we can strip those when ingesting into Prometheus but we'd have a slight preference to not store it at all.

I'm happy enough to work on a PR to add this, just wanted to start a discussion to see what you think.

**Comment by MacroPower** [comment]
Hello @mig4! The server included in this repo has a `--disable-user-metrics` flag already, but currently it only removes user_login and user_email labels from metrics (they are still included in the logs). In general my thought was this info is more often acceptable in logs as they tend to be more locked down and are not as affected by high cardinality. However I'd be okay with including something like `--disable-user-logs`. If you think this would be helpful, feel free to send a PR.

I believe the easiest way to implement this would be to remove user info from this slice:

https://github.com/MacroPower/macropower-analytics-panel/blob/18be95e87933686c94ef5fafa1b87609edbe4a7e/server/payload/handler.go#L110-L112

And then append it back if the `--disable-user-logs` flag is not set.

The only disclaimer is that this wouldn't do anything if you also use `--log-raw` since that flag disables all processing of the incoming payload before it's logged. I think this is fine, however.

**Comment by mig4** [comment]
Hi 👋 Thank you for your answer! I appreciate the details.

I have to admit we were thinking about stripping this on the frontend side and it didn't occur to me to check the backend flags 🤦 After looking into it a bit more now I think that `--disable-user-metrics` is actually enough for me as well.

I'm not too worried about the logs for now so I'm going to close this, but we might come back to it at some point in the future.
